name: Release Telodendria
run-name: Release Telodendria on ${{ forgejo.actor }}

on:
  push:
    tags:
      - 'v*'

jobs:
    "Release Telodendria":
        strategy:
            matrix:
                os: [alpine]
                arch: [aarch64]
        runs-on: ["${{ matrix.os }}", "${{ matrix.arch }}"]
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
              with:
                submodules: true
            - name: Archive submodules
              run: git submodule foreach --recursive 'git archive --format tar --prefix=$displaypath/ -o submodule.tar HEAD'
            - name: Archive repository
              run: git archive --format tar -o release.tar HEAD
            - name: Produce release archive
              run: |
                TOPDIR=$(pwd) git submodule --quiet foreach --recursive 'cd $TOPDIR; tar --concatenate --file=release.tar $displaypath/submodule.tar; rm -fv $displaypath/submodule.tar'
                gzip release.tar
                mkdir release
                mv release.tar.gz release/Telodendria-$GITHUB_REF_NAME.tar.gz
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: Telodendria-$GITHUB_REF_NAME.tar.gz
                path: release/Telodendria-$GITHUB_REF_NAME.tar.gz
            - name: Publish release
              uses: actions/forgejo-release@v3
              with:
                tag: $GITHUB_REF_NAME
                title: "Telodendria $GITHUB_REF_NAME"
                release-dir: release/
                release-notes: "docs/CHANGELOG.md"
                direction: upload
                prerelease: true
