blank_issues_enabled: false
contact_links:
  - name: General Matrix Room
    url: "https://matrix.to/#/#general:synapse.telodendria.org"
    about: |
      General discussion on Telodendria happens in this Matrix room. You
      may get quicker feedback from there.
